//Get all blocks from blockchain
GET http://0.0.0.0:3000/blocks

###

//Register new user in the system
POST http://0.0.0.0:3000/myroutes/register
Content-Type: application/json

{
    "mobilePhone":"5453543", 
    "email":"marchgridnev96@gmail.com", 
    "fio":"Алексей Гриднев 96" 
}

###

//Sign new document
//signers - emails of all signers
//public and private keys are without \n\n (change to 1 \n)
POST http://0.0.0.0:3000/myroutes/signdoc
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="publicKey"

-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCimgKeEULnmteC+gVHitKrY454\nbSTIQiLnf8WIaDYAEKApM5+KrgVry2aaJNKX0TxofIjk4bz/z6ran9/k5tdrLy+r\nxD7WgP/msNhvbZvKJli03BTXu38rjTMOGcQ9LsOqFJH+kQxG9TcsOE4JuNQVVMSt\n7Cu5VvqBi/JOaWiJTwIDAQAB\n-----END PUBLIC KEY-----\n
------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="privateKey"

-----BEGIN RSA PRIVATE KEY-----\nMIICXAIBAAKBgQCimgKeEULnmteC+gVHitKrY454bSTIQiLnf8WIaDYAEKApM5+K\nrgVry2aaJNKX0TxofIjk4bz/z6ran9/k5tdrLy+rxD7WgP/msNhvbZvKJli03BTX\nu38rjTMOGcQ9LsOqFJH+kQxG9TcsOE4JuNQVVMSt7Cu5VvqBi/JOaWiJTwIDAQAB\nAoGAS04oiCxWYA1GYlKIv2l7yASDpyJlNpnqsGxsf5BD8iPBCVPvP7r4p8O78Qe8\nwLMW1w1WGSqy7YawCjCg8NI4UZ0FDe81odnQrNfXEcBV97E2+OjNjf2JFlraeviN\nTgoNBLpwkiGryN5d+65LlSnAI42dnFPKj24LdhVw/rpaxAECQQDpemHygobL8op7\ncRS2ShVyX+IVBJcHE/ZyfPM1t7Ix830mgYATvfoZFkTK0sje6/Rx/aGMO5r8sBDD\nFHsSQRMvAkEAskle+G+mnqES/nI0U+5QpQD4S6osXmVfLOwru+YpW1HfZ+En1S0D\nfxcaVc3QQgsabVx9Llpuk0hhqaIkfAzj4QJBAJpC7xZRIYj9DnxzAZFTr4nrSjBC\n4RqfGPUaE4OJhKY2T5kydRIWMnmC2h78WBXZ5p+uSZ+i/ks4dUq/bHVqI6cCQChA\n8qVrKBaWzaAPjwsIOsMWlfkXgg8KGlQdOr6g9+N7d9KPfpveHvT59WM8JfJTaXMZ\nt9XYazDr3ckcJ9quWmECQDHKTW6MuD8wxufZzyZ8ZB4WpitlKEFIK0IOpHg9Be6V\nDyQgiI6ILh/uWusiBfD2JTSPNJNa28V5r1Ol7ggkukE=\n-----END RSA PRIVATE KEY-----\n

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="signers"

alexgridnev96@mail.ru,marchgridnev96@gmail.com
------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###

// Get my public key
POST http://0.0.0.0:3000/myroutes/getmypublic
Content-Type: application/json

{
    "email":"lexa1548@mail.ru"
}
###

// Send confirm code
POST http://0.0.0.0:3000/myroutes/sendcode
Content-Type: application/json

{
    "code":"dfsfdf",
    "recipient":"lexa1548@mail.ru"
}

###

//Check if doc is true
POST http://0.0.0.0:3000/myroutes/isdoctrue
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="email"

alexgridnev96@mail.ru
------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###
// Get date if signing
POST http://0.0.0.0:3000/myroutes/getdate
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="email"

alexgridnev96@mail.ru
------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###
//Check if all signers signed the document
POST http://0.0.0.0:3000/myroutes/checksignatures
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###
// Change user's keys
POST http://0.0.0.0:3000/myroutes/changekeys
Content-Type: application/json

{
"privateKey": "-----BEGIN RSA PRIVATE KEY-----\nMIICXQIBAAKBgQC+i2y+EIp96oArViivlQdpeq2VjaFIRZxCgmtyftDZGzd8wbSm\nLjjBhkzyt3iprDzobzUlgQlA3Z5dATvbKY7iveZ5GxRhvO9DT1c0GqeyB94BDKai\nx+JtGseoJr+wy6X6G7UfNQOUnx2jwhAimLfyMGa0gXKTB48yGX8R9kyJFQIDAQAB\nAoGAcQkJA1+QqM3aJts/25lPAlXSb+vLB7Kz1gjEcPGmN4Ubz5ih8Atvg+6F617H\n5+/TWhfOsWbw9FgEQCwhNAxdRENKZMjaM7amSJMP7vbkMhnqWw7bKvPcQACXn8De\nlb7hBGKlO3XTv5Z8OO5qMnexV3lgm0WU2yCk9J8j412EiGkCQQDgtNVFqKM56KXZ\nKGxFIeO/Yj97iavAY1eigPc1fMEtmc8wpne++VBuBnALggUCAwoIceBgHhWZffWd\nrbOR5fpHAkEA2RSqsyyG/0d3YUrvxXzlkN9jr/eyYjMIDs4LRKJ9N+MwdvizNuKG\nZI7S0lXMIv0HKlAq1hen5DJBvNTyjUdzwwJBAMK+Ni/ezUe8xy+DBwKLMnSFU3tf\nf0iHUEX3+0eRzWIV8Si6vQD31arlTWnLz0dFFwbmmozyxcl3Ds0O45fIdrUCQDky\njNew/9D7j6T/DbZHdmV5ttaCuWnOcG0WNTncZon3PqnaVb48aZTNXRc2rBb7/ItV\nnDPU/9PMui17Hn3DOekCQQDVzHcV6sGie80Q0oe+J1GlqMKwFu6wWBQk4GsyzC89\n/HCzNopEqggF12VnTH45RqVFagzvT+zx5NP3rLqOaJew\n-----END RSA PRIVATE KEY-----\n",
"publicKey": "-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+i2y+EIp96oArViivlQdpeq2V\njaFIRZxCgmtyftDZGzd8wbSmLjjBhkzyt3iprDzobzUlgQlA3Z5dATvbKY7iveZ5\nGxRhvO9DT1c0GqeyB94BDKaix+JtGseoJr+wy6X6G7UfNQOUnx2jwhAimLfyMGa0\ngXKTB48yGX8R9kyJFQIDAQAB\n-----END PUBLIC KEY-----\n"
}
###
//Check if my document signature is true
POST http://0.0.0.0:3000/myroutes/checkmysignature
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="publicKey"

-----BEGIN PUBLIC KEY-----\nMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCU3wcUmLLmf1WBqxAik5OWRZfR\n573j60RGARCi1DjLtxjXT9F1tdFCrpKqvaQwJTOZ9leaguFvHn5pIxxUGDLpwsHR\nIctayQohHCFnnfkufu8ulL9Ao96OArS/WmIQ5ThX5uxJaq+Wlw+3baMK+10MFH9B\n/7ORDcL8T/AeFg44awIDAQAB\n-----END PUBLIC KEY-----\n
------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###

//Check if another user's document signature is true by email
POST http://0.0.0.0:3000/myroutes/checksignature
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="email"

alexgridnev96@mail.ru
------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C--

###
//Check if another user's document signature is true by mobile phone

POST http://0.0.0.0:3000/myroutes/checksignaturebyphone
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryE19zNvXGzXaLvS5C

------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="mobilePhone"

545343
------WebKitFormBoundaryE19zNvXGzXaLvS5C
Content-Disposition: form-data; name="document"; filename="testDoc.pdf"
Content-Type: application/pdf

< ./testDoc.pdf

------WebKitFormBoundaryE19zNvXGzXaLvS5C--